### ISSUE TITLE
Custom Styles

### ISSUE THREAD

**Issue by mbuttler** [DSchau/gatsby-remark-toc#2]
Maybe I'm missing something, but I can't figure out how to apply custom styles to the TOC. Do you have any pointers?

**Comment by DSchau** [comment]
Hi Matt!

So this will just generate HTML (e.g. h1/h2/etc.) so you'd just style those as you would anything else!

If you'd like more flexibility for styling just the TOC, you may look into the `tableOfContents` resolver made available when querying Markdown nodes from Gatsby.

Hope that helps!

**Comment by mbuttler** [comment]
Hi Dustin,

That's what I thought, but customizing unwrapped tags causes all of the styles in my markdown to change as well.

Is it at all possible to wrap the TOC in a class so that I can specifically style the TOC elements and nothing else?

**Comment by DSchau** [comment]
Perhaps look into the second thing I mentioned (i.e. `tableOfContents` on the Markdown node). That should do something similar, and should give you an array of styleable elements!

Otherwise, I can look into that, but I think the approach I specified will be inherently more flexible and useful!

**Comment by mbuttler** [comment]
🤔 

Maybe I'm not sure what you mean, but maybe we can kinda help each other out here. If you can explain to me how to do that, I can write up process docs that you can add to your Readme to prevent people like me from asking the same question 😆

**Comment by DSchau** [comment]
Sure, except I think that's almost tangential to this plugin!

Here's an example I just created -> https://github.com/DSchau/gatsby-table-of-contents-example

In particular, you'll find the following file illustrative: https://github.com/DSchau/gatsby-table-of-contents-example/blob/master/src/pages/example.js

**Comment by mbuttler** [comment]
I've messed around with this for a while and I still can't get it to work. I really think wrapping it in a 'toc' class would be pretty helpful. That's kind of the idiom you get with Kramdown and Ruby.

**Comment by DSchau** [comment]
PRs welcome :)
